kind: Service
apiVersion: v1
metadata:
  name: infofabric-mview-svc
  labels:
    app: infofabric-mviews
spec:
  type: NodePort
  selector:
    app: infofabric-mviews
  ports:
    - port: 1521
      targetPort: 1521
      protocol: TCP
      nodePort: 31521
