apiVersion: v1
kind: Service
metadata:
  labels:
    app: fwd-proxy-apache2
  name: fwd-proxy-apache2
spec:
  ports:
  - port: 8085
    protocol: TCP
    targetPort: 80
  selector:
    app: fwd-proxy-apache2
